### ISSUE TITLE
0 == 0 -> false

### ISSUE THREAD

**Issue by quartata** [cheddar-lang/Cheddar#81] opened 2016-10-02 17:08 UTC
**Version:** v1.0.0-beta.50

### Problem

`==` does not work properly for `0` and `0`.

    cheddar> 0 == 0
    false
    cheddar> 1 == 1
    true

### Desired Behavior

Comparing two literals or lvalues that are both `0` should yield `true`.

### How to Reproduce

 1. Simply compare two zeros.

**Comment by vihanb** [comment] 2016-10-02 20:59
Fixed in 9d2df293ed6d502bccc57da194d752eec22f157c

**Comment by ConorOBrien-Foxx** [comment] 2016-10-09 00:44
uh oh. is it borked again?

**Comment by vihanb** [comment] 2016-10-09 01:01
@ConorOBrien-Foxx it was never fixed but I know exactly what the problem is, I just need to fix it

**Closed** 2016-10-25 01:29 UTC
Labels: bug, interpreter
