### ISSUE TITLE
Arrays are not working

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#25] opened 2016-06-25 03:48 UTC
**Version:** 0.3.0
## Problem
When i enter an array literal, it says `Symbol(UNLINKED_CLASS)` in scary red font.

**Comment by vihanb** [comment] 2016-06-25 03:50
Yeah >_> this is caused by stupid cyclic dependencies

**Comment by vihanb** [comment] 2016-06-28 00:53
Fixed in 5be24692f78834ba9cb3b6f14035d141c978558a

**Closed** 2016-06-28 00:53 UTC
Labels: bug, evaluation, interpreter, status:repro
